package com.openvote;

import java.io.IOException;
import java.util.*;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import static com.googlecode.objectify.ObjectifyService.ofy;
 

@SuppressWarnings("serial")
public class CastVoteServlet extends HttpServlet {

	public void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws IOException {
	}
	
    public void doPost(HttpServletRequest req, HttpServletResponse resp)
            throws IOException {
    	String candidate_str = req.getParameter("candidate");
    	
    	// cast real vote
    	Vote vote = new Vote(Candidate.valueOf(candidate_str).ordinal());
    	ofy().save().entity(vote).now(); 	
    	//TODO: verify that the autogenerated id is unique
    	
    	// cast vote for all fake candidates
    	ArrayList<Vote> fakeVotes = new ArrayList<Vote>();
		for (Candidate c: Candidate.values()) {
			Vote fakeVote = new Vote(c.ordinal());
    		ofy().save().entity(fakeVote).now();
    		fakeVotes.add(fakeVote);
    	}
    	
    	// pass real and fake vote information to display keys page
		req.setAttribute("realVote", vote);
		req.setAttribute("fakeVotes", fakeVotes);
		req.setAttribute("numFakeVoteBatches", 1);
		RequestDispatcher dispatcher = getServletContext().getRequestDispatcher("/displayVoteKeys.jsp");
		try
		{
			dispatcher.forward(req, resp);
		} catch (ServletException e)
		{
			e.printStackTrace();
		}
		
    }

}
